{% set version = "4.6.1" %}

package:
  name: libnetcdf-parallel
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: a2fabf27c72a5ee746e3843e1debbaad37cd035767eaede2045371322211eebb

build:
  number: 11
  skip: True  # [win and vc<14]
  run_exports:
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    - {{ pin_subpackage('libnetcdf-parallel') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
  host:
    - bzip2
    - curl
    - zlib
    - {{ mpi }}
    - hdf4
    - hdf5 1.10.4 mpi_{{ mpi }}_*
    - jpeg
  run:
    - bzip2
    - curl
    - zlib
    - {{ mpi }}
    - hdf4
    - hdf5
    - jpeg

test:
  commands:
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf${SHLIB_EXT}  # [not win]
    - nc-config --all  # [not win]
    # All these endpotins failed at some point due to various reasons.
    #- ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
    #- ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
    #- ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
    #- ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
    #- ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data'

extra:
  recipe-maintainers:
    - groutr
    - kmuehlbauer
    - ocefpaf
    - mingwandroid
    - msarahan
    - beckermr
